name: Deploy static page

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Define a job
jobs:
  deploy:
    # Specifies the environment where the deployment happens.
    # It is useful for managing deployment environments
    # like staging, production, or custom ones.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Specify the runner environment
    runs-on: ubuntu-latest

    # Execute sequence of the following steps    
    steps:
      # Checkout a Git repository at a particular version
      - name: Checkout
        uses: actions/checkout@v4
      # Install dependencies listed in the package.json file
      # of the project. Creates a node_modules directory where 
      # the installed packages are stored.
      # Updates the yarn.lock file if needed, unless otherwise specified.
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      # Compile or package a project for production
      - name: Build
        run: yarn build
      # Enable Pages, extract various metadata about a site, 
      # and configure some supported static site generators
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      # Prepare your static assets to be deployed to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Specify build output path
          path: build
      # Deploy an artifact as a GitHub Pages site    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
